micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: 'postgres'
    password: 'pass'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    entity-scan:
      packages:
        - com.demo.entity
        - com.demo.repository
        - com.demo.service
        - com.demo
mongodb:
  uri: mongodb://localhost:27017/myMongo

db:
  name: 'loyaltyEntity'
  collection: 'loyaltyEntity'


